# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_14,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_14 ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then
          rev_base
        else
          "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "AFLplusplus-4.21.0-aA1y4dZxAADpqYGALLosVdQlaX0yTfMPLbg_p-f-zeSg";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "git+https://github.com/allyourcodebase/AFLplusplus?ref=refs/pull/7/head#12381a97cf5afccc87da4dba680fbef31519bc47";
      hash = "sha256-hhapvObfBtyea3zlVVLPJa7Ce+mLDPduPRz8wIdlxG8=";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-EffHfTfP9uf2WsfMVbq3kB4MYgjoRaOHZDlNBO1WezA=";
    };
  }
  {
    name = "afl_kit-0.1.0-NdJ3chAdAABiOcwXk_aKGpzGr3ou0qIxAVnVjUqXyvii";
    path = fetchZigArtifact {
      name = "afl_kit";
      url = "git+https://github.com/jcollie/zig-afl-kit#98859bc815166d253764b498669ec4df75a15c37";
      hash = "sha256-03qwnL1GsfWu+mCaJLIkKYYjJgeGiRbWbtq1aaVKX7I=";
    };
  }
  {
    name = "cbor-1.0.0-RcQE_CUwAQChkeU-LO-eTSbLAdRox-wuxUGmi2nDAWri";
    path = fetchZigArtifact {
      name = "cbor";
      url = "git+https://github.com/kristoff-it/cbor?ref=zig-0.15#66c3784a6b1cf56485d462502167ec2ce402e8fb";
      hash = "sha256-EdT3Kg2opvjrD6zBUEfuJGAY7495y60FQV6mHQC8qn8=";
    };
  }
  {
    name = "flow_syntax-0.1.0-X8jOoXwNAQCYQg3lzNZrx0aNx9xGtWStsgcxv8IZ1olI";
    path = fetchZigArtifact {
      name = "flow_syntax";
      url = "git+https://github.com/kristoff-it/flow-syntax?ref=zig-0.15#42b600c9e111b7836f2aed9e229637c7d8e63a25";
      hash = "sha256-bL98gB/lwrEQebMHVhjSN+Ct1REqSIvnMGlsZ2XjKOM=";
    };
  }
  {
    name = "N-V-__8AALShqgXkvqYU6f__FrA22SMWmi2TXCJjNTO1m8XJ";
    path = fetchZigArtifact {
      name = "frameworks";
      url = "git+https://github.com/hexops/xcode-frameworks.git#8a1cfb373587ea4c9bb1468b7c986462d8d4e10e";
      hash = "sha256-b1Ay3GfBHwubnrGi4lflPiaqGfzWtABEbEiE8+ZTL90=";
    };
  }
  {
    name = "cmark_gfm-0.1.0-uQgTK6WZFwCG9y7_Z0IkCINtmMTwvEZTyVh_6nsaMVPq";
    path = fetchZigArtifact {
      name = "gfm";
      url = "git+https://github.com/kristoff-it/cmark-gfm#b96c27a5152b9124d657dee7fb1186d0a13c1fe4";
      hash = "sha256-NlTZ5if3h1zZjJs0JTMB8SsvTQM+4OSsScvFUbfq9nQ=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
    path = fetchZigArtifact {
      name = "known_folders";
      url = "git+https://github.com/ziglibs/known-folders#aa24df42183ad415d10bc0a33e6238c437fc0f59";
      hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtTTAADUOhGKM0sxzG4eMkNQxRvx9e5dfHVyaeA3";
    path = fetchZigArtifact {
      name = "known_folders";
      url = "git+https://github.com/ziglibs/known-folders#ab5cf5feb936fa3b72c95d3ad0c0c67791937ba1";
      hash = "sha256-Pdn/nUclhHBB1COTzNNR5ysE13h6uLOFJjuFrasv/2I=";
    };
  }
  {
    name = "lsp_kit-0.1.0-bi_PL18tCgAMyrZ0tgn_0PXnGEvxGWeNkkRygfe9pX9u";
    path = fetchZigArtifact {
      name = "lsp_kit";
      url = "git+https://github.com/zigtools/lsp-kit#4835b9d3d3cf732fe1830189d81f331c68fb3e77";
      hash = "sha256-PqTlZcOow9vGLzI40zvqDI18OhJKzMg8RFLxB4x88/c=";
    };
  }
  {
    name = "lsp_kit-0.1.0-bi_PL5YyCgA2QFEza6llr2Uy08QUQsWBu2wKvtr8tbLx";
    path = fetchZigArtifact {
      name = "lsp_kit";
      url = "git+https://github.com/kristoff-it/lsp-kit?ref=zig-0.15#01c14e592d25dc57dfebba27b8bd2b4aa91c1140";
      hash = "sha256-HZ529k2WepqJEZ60y7bQ36qCFF5HjtiqQCpi66Rr0+8=";
    };
  }
  {
    name = "mime-3.0.0-zwmL--0gAAByELrj57sRm2EFBRzjKLFrMgHQcs7sFZev";
    path = fetchZigArtifact {
      name = "mime";
      url = "git+https://github.com/kristoff-it/mime#a2ed0cba3b1463217168034ffed8c1604e72598d";
      hash = "sha256-j/O/6pJg0hj3ytAMVBQwGjCRtaR+GYy8X7oqfIpuRi8=";
    };
  }
  {
    name = "scripty-0.1.0-LKK5O7f4AADajW5A_FsfNQBqRts7MiIZZkGVXkXDCCcg";
    path = fetchZigArtifact {
      name = "scripty";
      url = "git+https://github.com/jcollie/scripty#17a8ee8ada33bd45329d96671e25c7f09e998144";
      hash = "sha256-TcXigINJ9ifsVha5i+BpACcZXHiWYJjbnwuADix+nRo=";
    };
  }
  {
    name = "superhtml-0.4.0-Y7MdPIzWDQBLKgxL-eJsOlDbtwi2zlV8ZiRLDL9U7s5p";
    path = fetchZigArtifact {
      name = "superhtml";
      url = "git+https://github.com/jcollie/superhtml#a91bf7cda017e1cf4ef82acfebd380d646146c2c";
      hash = "sha256-gyVmpYDmiQBGW0sDSmjfqJ6YrqSDzp96HF44AI0piJI=";
    };
  }
  {
    name = "supermd-0.1.0-3Mco3FOSWACBcvUXfmBu1tsVRP3o_R5TXHl5-QCcBnkv";
    path = fetchZigArtifact {
      name = "supermd";
      url = "git+https://github.com/jcollie/supermd#d73a30b34fb31cfb2389a9a9f14a418231fadabb";
      hash = "sha256-h8DoDwfx9mO6ls9GwQwDFVoLacbZGgZG9FajL5pPFc4=";
    };
  }
  {
    name = "tracy-0.0.0-4Xw-1pwwAABTfMgoDP1unCbZDZhJEfict7XCBGF6IdIn";
    path = fetchZigArtifact {
      name = "tracy";
      url = "git+https://github.com/kristoff-it/tracy#67d2d89e351048c76fc6d161e0ac09d8a831dc60";
      hash = "sha256-BKo1bhua/u+f5Z//ailur5aSHZWp3GiC0iwmVLrGZkE=";
    };
  }
  {
    name = "tree_sitter-0.22.4-150-g7e3f5726-z0LhyN88UicDHlr22vQnOZ3DW9NWN1gOhDwLuCRXvrh2";
    path = fetchZigArtifact {
      name = "tree_sitter";
      url = "https://github.com/neurocyte/tree-sitter/releases/download/master-f1f032d24f621e2ee4deab1c424d3bf9fb809f6e/source.tar.gz";
      hash = "sha256-w0164ZvB2jHRRlumkwGsROZHInHj5z+Ny4e/x0tPrtU=";
    };
  }
  {
    name = "wuffs-0.4.0-alpha.9+3837.20240914-3CHJgcMFAACyPvxsC7b48pJv9dPkPa4pSrB2VFbCXTfK";
    path = fetchZigArtifact {
      name = "wuffs";
      url = "git+https://github.com/allyourcodebase/wuffs#5822dc06c75b30d53082debf68c90193cb2b2608";
      hash = "sha256-Ung7shyFg+/I5Po393tWMp6Jb0Ia14pRJOUF36fr71c=";
    };
  }
  {
    name = "N-V-__8AANEmUgA6aZZZKbfNMv6DSs5In7CDFU6nInu_Y6aY";
    path = fetchZigArtifact {
      name = "wuffs";
      url = "https://github.com/google/wuffs-mirror-release-c/archive/90e4d81a6a8b7b601e8e568da32a105d7f7705e5.tar.gz";
      hash = "sha256-3b68j7dAXnqRd+/fvfDfGK0CtgcxHZ5gSVnHwPYjavQ=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk0J9AgCVa0nnyL0lNY9Xa9F68hHq-ZarhuXNV-Jb";
    path = fetchZigArtifact {
      name = "zeit";
      url = "git+https://github.com/sam701/zeit?ref=zig-0.15#46583c4695bade6841a558c0ce5648426b556214";
      hash = "sha256-IvXaqAzaWi3E1XBqQltCBFoRmXehZkVol3/RZwOsAKg=";
    };
  }
  {
    name = "ziggy-0.1.0-kTg8v5pABgDztlefWHceH-Sh8tVveguFC61QkmLkIRaA";
    path = fetchZigArtifact {
      name = "ziggy";
      url = "git+https://github.com/kristoff-it/ziggy#4353b20ef2ac750e35c6d68e4eb2a07c2d7cf901";
      hash = "sha256-7XZNKUrOkpPMge6nDSiEBlUAf7dZLDcVcJ7fHT8fPh4=";
    };
  }
]
